sudo: required

branches:
  only:
    - master

language: c++

compiler:
  - gcc
  - clang

notifications:
  email: false

env:
  - ARCH_TRAVIS_CONFIRM_YES=1

arch:
  packages:
    - cmake
    - clang
    - clang-tools-extra
    - llvm-libs
    - llvm
  script:
    - if [ "$CXX" = "g++" ]; then ./scripts/travis.sh; fi
    - if [ "$CXX" = "clang++" ]; then ./scripts/travis-coverage.sh; fi

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
