sudo: required

branches:
  only:
    - master

notifications:
  email: false

env:
  - ARCH_TRAVIS_CONFIRM_YES=1

arch:
  packages:
    - cmake
    - clang
    - clang-tools-extra
    - llvm-libs
    - llvm
  script:
    - ./scripts/travis.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
